# Generated by Django 4.2.7 on 2023-11-15 16:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedaia', '0003_nukhba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedaia',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='bedaia',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='nukhba',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='nukhba',
            name='logo',
        ),
        migrations.AddField(
            model_name='bedaia',
            name='firstdiscription',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='bedaia',
            name='firstpic',
            field=cloudinary.models.CloudinaryField(default=' ', max_length=255, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='bedaia',
            name='seconddiscription',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='bedaia',
            name='secondpic',
            field=cloudinary.models.CloudinaryField(default=' ', max_length=255, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='nukhba',
            name='firstdiscription',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='nukhba',
            name='firstpic',
            field=cloudinary.models.CloudinaryField(default=' ', max_length=255, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='nukhba',
            name='seconddiscription',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='nukhba',
            name='secondpic',
            field=cloudinary.models.CloudinaryField(default=' ', max_length=255, verbose_name='Image'),
        ),
    ]
