# Generated by Django 4.2.7 on 2023-11-15 17:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedaia', '0005_alter_bedaia_firstdiscription_alter_bedaia_firstpic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedaia',
            name='firstdiscription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bedaia',
            name='seconddiscription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bedaia',
            name='secondpic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='nukhba',
            name='firstdiscription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='nukhba',
            name='firstpic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='nukhba',
            name='seconddiscription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='nukhba',
            name='secondpic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
    ]
