# Generated by Django 4.2.7 on 2023-11-16 07:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bedaia', '0006_alter_bedaia_firstdiscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedaia',
            name='forthpic',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bedaia',
            name='thirdpic',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nukhba',
            name='forthpic',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nukhba',
            name='thirdpic',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bedaia',
            name='firstpic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
    ]
