# Generated by Django 4.2.7 on 2023-11-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bedaia', '0007_bedaia_forthpic_bedaia_thirdpic_nukhba_forthpic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
